name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
   push:
   workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was a ${{ secrets.PAT }} secrets." 
      - run: echo "This job is ${{ var.MY_NAME}} !"

      - name: Check out repository code
        uses: actions/checkout@v4
# name: Github Java app
# on:
#   push:
#     branches:
#       - main
#       - develop
#   workflow_dispatch:
  
# jobs:
#   my_first_job:
#     runs-on: ubuntu-latest
#     # self-hosted
    

#     steps:
    
#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         java-version: '17'
#         distribution: 'zulu'

#     - name: Show Java version
#       run: "java -version"

#     - name: Checkout code
#       uses: actions/checkout@v4
#       with:
#         ref: develop

#     - name: Show directory
#       run: 'pwd'

#     - name: List files
#       run: 'dir'

#     - name: Install Dependencies
#       run: 'mvn compile'

#     - name: Build application
#       run: 'mvn package -DskipTests'

#     - name: Test application
#       run: 'mvn test'

